Quiz 4

In [1]:
import pandas as pd
import numpy as np

table = pd.read_csv('./0050.csv', index_col='Date')

table = table[(table['Open']>table['Close'])]
table.sort_values(['Amount','Open'], inplace=True, ascending=False)
print(table)
ans = table.head(3).to_numpy(dtype='i4')
print(ans)

             Open   High    Low  Close  Amount
Date                                          
2011/8/5    55.70  55.70  54.45  54.45   93525
2011/8/8    54.30  54.65  51.40  53.50   88159
2018/10/11  80.15  80.15  77.35  77.40   68552
2020/3/19   71.00  71.00  67.25  68.55   68038
2011/9/23   50.50  50.85  49.93  50.35   64026
...           ...    ...    ...    ...     ...
2019/10/21  87.95  88.00  87.75  87.85    1078
2017/10/24  84.50  84.50  84.20  84.40    1072
2017/11/24  85.25  85.30  84.95  85.15    1069
2017/11/14  84.30  84.30  83.95  84.15    1016
2017/11/8   85.20  85.20  84.95  84.95     810

[1122 rows x 5 columns]
[[   55    55    54    54 93525]
 [   54    54    51    53 88159]
 [   80    80    77    77 68552]]
